---
platform: linux

image_reousrce:
  type: docker-image
  source: { repository: busybox}

inputs:
- name: repo
- name: app-name

outputs:
- name: prepare-manifest

run:
  path: sh
  args: [repo/tasks/prepare-manifest.sh]
